// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  accordion: defineAsyncComponent(() => import("./Accordion/index.vue")),
  advert: defineAsyncComponent(() => import("./Advert/index.vue")),
  carousel: defineAsyncComponent(() => import("./Testimonials/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
});
